### PR TITLE
added pointcloud filter

### PR DESCRIPTION
**Pull request by JasperSuess**

### CODE REVIEW

**Comment by Martin-Oehler** [comment]
The plugin works well, thanks!

I have a few remarks regarding usability:
* For an easier overview, all filtering options could be in a sub-group
* There should be a button to enable filtering, which is off by default
* There are two entries named "Axis"
* Change the "Frame" option to a drop down box with the entries "Message Header" and "Fixed Frame"

**Comment by Martin-Oehler** [comment]
Great changes, it is much more usable now.

For some reason, there is a lot of white space below the sub-group. Can you replicate that?
image

And we should probably capitalize the filtered axis names to stay consistent.

**Comment by Martin-Oehler** [comment]
I just noticed, that the console is spammed with
```
Failed to find match for field 'rgb'.
```
when filtering is activated. If I remember correctly, you can disable this warning with
```
pcl::console::setVerbosityLevel(pcl::console::L_ERROR);
```

**Comment by JasperSuess** [comment]
Yep, I just noticed the whitespaces too. It's now properly implemented.
I couldn't reproduce the console messages but did add the verbosity level.

**Comment by StefanFabian** [comment]
Thank you for merging @Martin-Oehler.
@JasperSuess could you please add a description and a small example image to the README?

**Comment by JasperSuess** [comment]
@StefanFabian Done.

**Pull request merged**
